import {
  AudioLines,
  Bot,
  Boxes,
  Brain,
  Braces,
  ChartNoAxesCombined,
  Cloud,
  Code2,
  Coffee,
  Container,
  Cpu,
  Database,
  FileJson,
  Filter,
  GitBranch,
  Hexagon,
  Layers,
  MessageSquare,
  Mic,
  Network,
  ScanSearch,
  Server,
  Share2,
  Sigma,
  Sparkles,
  Table2,
  Terminal,
  Workflow,
  type LucideIcon,
} from "lucide-react"

const icons: Record<string, LucideIcon> = {
  Python: Code2,
  SQL: Database,
  Java: Coffee,
  JavaScript: Braces,
  "Artificial Intelligence": Brain,
  "Machine Learning": Cpu,
  "Generative AI": Sparkles,
  "Large Language Models": MessageSquare,
  "Prompt Engineering": Terminal,
  "Model Evaluation": ScanSearch,
  "Feature Engineering": Filter,
  "Retrieval-Augmented Generation": Share2,
  Embeddings: Hexagon,
  "Multi-Agent Systems": Network,
  "AI Workflow Automation": Workflow,
  Pandas: Table2,
  NumPy: Sigma,
  "Scikit-learn": ChartNoAxesCombined,
  "Exploratory Data Analysis": ChartNoAxesCombined,
  "ETL Pipelines": Workflow,
  "Data Cleaning": Filter,
  "Data Normalization": Layers,
  "Data Visualization": ChartNoAxesCombined,
  "KPI Reporting": ChartNoAxesCombined,
  PostgreSQL: Database,
  MySQL: Database,
  MongoDB: Database,
  Hadoop: Server,
  "Apache Spark": Sparkles,
  Hive: Boxes,
  Git: GitBranch,
  GitHub: GitBranch,
  Docker: Container,
  "Cursor AI": Sparkles,
  ChatGPT: MessageSquare,
  "GitHub Copilot": Bot,
  "REST APIs": Share2,
  JSON: FileJson,
  "AWS QuickSight": Cloud,
  Azure: Cloud,
  "Google Cloud Platform": Cloud,
  Vapi: Mic,
  Ollama: Bot,
  "RAG Applications": Share2,
  "AI Agents": Bot,
}

export function SkillGlyph({ name }: { name: string }) {
  const Icon = icons[name] ?? AudioLines
  return <Icon size={18} strokeWidth={1.6} aria-hidden="true" />
}
